happy.sentenceSpecs = [
	[['Cosmos don\'t care;', 'This is a disaster!', 'I better not screw up!'], ['everything is trivial', 'obsession is crucial', 'the responsibility is immense'], ['in the vastness', 'in my small'], ['of the universe.', 'of my brain.', 'of some jerk\'s opinion.']],
	[['Ain\'t no thang;', 'Worse than it seems;', 'Oh my god!'], ['this is probably', 'this is definitely'], ['not as bad', 'worse', 'just as bad'], ['as it seems.', 'as the knot in my stomach tells me.']],
	[['Challenge accepted;', 'Time to fold\'em;', 'I give up;'], ['I show assholes', 'I hide from assholes', 'I submit to assholes'],['I can deal.', 'I can\'t deal.', 'I give in.']],
	[['Maslov\'s got my back;', 'I\'ll never survive;', 'This will kill me;'], ['All I need', 'So much is needed'], ['is H20 and Oxygen!', 'is impossible to get.', 'is the approval of everyone.']],
	[['Drop the dead weight;', 'Keep carrying this baggage;', 'Beat myself up;'], ['I\'m a better person', 'I\'m such a lose'], ['if I forgive myself', 'because I hold onto hate', 'continuously punishing myself'], ['and look to', 'and am blind to'], ['the future.', 'my failings.', 'the shame.']],
	[['More Badass than I think;', 'Such a wimp;', 'Can\'t handle this;'], ['I\'m stronger', 'I\'m weaker', 'I\'m more pathetic'], ['than I think.', 'and it\'s hopeless.']],
	[['I understand;', 'I\'m confused;', 'I\'m angry;', 'I\'m scared;'], ['I figure out', 'I give up on', 'I\'m frustrated by'], ['why people and things', 'that it doesn\'t make sense'], ['are this way.', 'should be another way.']],
	[['I can', 'I can\'t', 'I won\'t'], ['succeed,', 'fail,', 'give up,'], ['but I', 'not!'], ['might fail.', 'will definitely fail.', 'don\'t have to try.']],
	[['You\'re not the only one;', 'You are entitled to everything;', 'Poor baby;'], ['others', 'no one else'], ['deal with', 'throw tantrums', 'pout'], ['and live through', 'and can\'t handle', 'and give up'], ['the same thing.', 'totally different things.']],
	[['Feast on the light;', 'What a drag;', 'It doesn\'t matter;'], ['Somehow,', 'No way,', 'Never,'], ['somewhere,', 'nowhere,', 'out of reach,'], ['there is awesomeness', 'there is meaninglessness', 'there is despair'], ['I can drive towards!', 'I must know about to get to.', 'which is not worth it.']],
	[['Trust myself;', 'Over think it;', 'Obsess;'], ['I trust', 'I fear', 'I micro-manage'], ['my body to heal me,', 'my body to break me,', 'my body to wimp out,'], ['my instincts to guide me,', 'wishful thinking to mislead me', 'my fears to wreck me'],  ['and my intellect to understand it all.', 'and my intellect to fret over it all.']]
];
