happy.sentenceSpecs = [
	// ['Insecure and power-hungry try to intimidate me, but I know I\'m smart, observant, strong, and calm enough to stand up to them', ['!', '.']],
	// [['I am best', 'I am worst', 'I am hopeless'], ['when I feel', 'when I\'m numb to'], ['success', 'losing', 'dropping the ball'], ['is possible', 'is infeasible', 'is unlikely'], ['and great', 'and worthless', 'and ok'], ['and failure', 'and abject humiliation', 'and tragedy'], ['is disappointing', 'is humiliating', 'is irrecoverable'], ['but nerfed', 'but biting', 'but devastating'], ['!', '.']],
	// [['I see', 'I am blind to', 'I don\'t notice'], ['the tension', 'the panic', 'the immense pressure'], ['of all situations', 'of nothing'], ['in a way', 'in only one way', 'with ignorance'], ['that maximizes', 'that minimizes', 'that can\'t reach'], ['fun', 'boringness', 'opression'], ['and excitement', 'and fear', 'and terror'], ['!', '.']]
	// [['I am', 'No one is'], ['mostly', 'never'], ['happy', 'sad', 'distraught'], ['!', '.']],
	[['Success', 'Failure', 'Disaster'], ['is awesome', 'is ok', 'is horrible'], ['failure', 'collapse', 'annihilation'], ['is acceptable', 'is unthinkable', 'is devastating'], ['!', '.']],
	[['Winning means', 'Asshattery means', 'Smugness means'], ['learning,', 'calcification,', 'I know everything,'], ['humility,', 'gloating,', 'I told you so,'], ['and celebration;', 'and it wasn\'t good enough;', 'and no breaks;'], ['losing', 'ruin', 'dooming'], ['still means', 'is the end of'], ['learning', 'self flagellation', 'shame'], ['and humility', 'and resentment', 'and jealousy'], ['!', '.']],
	[['I\'m proud of', 'I\'m overconfident about', 'I\'m obnoxious with' ], ['my strengths', 'my adequacies', 'my deceptions'], ['and find humor in', 'and hate', 'and berate myself over'], ['my weaknesses', 'my ineptitude', 'my worthlessness'], ['!', '.']],
	[['Triumph', 'Undeserved luck', 'Passable work'], ['is awesome,', 'is ok,', 'is alright,'], ['inspiring,', 'forgettable,', 'bland,'], ['and fun;', 'and boring;', 'and stressful;'], ['misadventures', 'catastrophes', 'wrecks'], ['are acceptable,', 'are unacceptable,', 'are repugnant,'], ['common,', 'infamous,', 'mortifying,'],  ['and recoverable from', 'and permanent stains', 'and unrecoverable from'], ['!', '.']],
	[['I have high', 'I have low', 'I don\'t have any'], ['self-esteem', 'self-doubt', 'self-loathing'], ['and my confidence', 'and my fear', 'and my insecurity'], ['can withstand', 'buckles to', 'whithers in front of'], ['anything', 'nothing'], ['!', '.']],
	[['Haters', 'My masters'], ['gonna hate', 'crush my soul', 'enrage me', 'make me hate'], ['!', '.']],
	[['Keeping my cool', 'Freaking out', 'Blaming others'], ['is always', 'is never'], ['the way to win', 'evidence of weaknesses', 'not enough'], ['!', '.']],
	[['Everything is gonna', 'Nothing will ever'], ['be alright,', 'be a trainwreck,', 'be a tragedy,'], ['everything is gonna', 'nothing is will ever'], ['be OK,', 'be ruinous,', 'be disappointing,'], ['yeah', 'no', 'whatever'], ['!', '.']],
	[['Things are', 'Stupidity is'], ['just challenging enough', 'too hard', 'too easy and boring'], ['and important enough', 'and totally crucial', 'and too ridiculous'], ['to be fun', 'to panic me', 'to be boring'], ['!', '.']],
	[['I am', 'Don\'t bother with'], ['in awe of', 'terrified of', 'unaware of'], ['and freed by', 'and devestated by', 'and saddened by'], ['my insignifigance', 'my overinflated importance'], ['in the face of', 'denying'], ['the universe', 'this shithole', 'my own world'], ['!', '.']],
];
