happy.sentenceSpecs = [
	// [['I have a fire within', 'I have a whimper within', 'I have a void within'], ['that I harness the power of', 'that I loose controlof', 'that overwhelms me'], ['!', '.']],
	[['I see', 'I am blind to', 'I disregard'], ['and feel', 'and can\'t grasp', 'and can\'t imagine'], ['the benefits to', 'the drudgery of', 'the worthlessness of'], ['all the things', 'nothing'], ['I want to do', 'I\'d hate to do', 'I don\'t care to'], ['!', '.']],
	[['I do stuff', 'I procrastinate', 'I lay around'], ['to have an awesome time', 'for no good reason', 'for spite'], ['laughing,', 'crying,', 'sighing,'], ['playing,', 'being bored,', 'being a slave,'], ['making great things,', 'getting by,', 'fiddling with crap,'], ['helping friends,', 'avoiding enemies,', 'hiding from people,'], ['learning,', 'forgetting,', 'remaining ignorant,'], ['improving,', 'getting worse,', 'being frustrated,'], ['and winning', 'and losing', 'and failing'], ['!', '.']],
	[['I forge', 'I leave', 'I can\'t make'], ['my ideas', 'my stupidity'], ['in the fire', 'in the quagmire', 'in the mud'], ['of reality', 'of absurd expectations', 'of lies'], ['!', '.']],
	[['I am motivated', 'I am frustrated', 'I am bored'], ['and energized', 'and tired', 'and fed up'], ['!', '.']],
	[['I see', 'I miss', 'I can\'t imagine'], ['realistic', 'impossible', 'absurd'], ['success', 'failure', 'disaster'], ['!', '.']],
	[['I know', 'I\'m not sure', 'I forget'], ['I can', 'I can\'t', 'I won\'t'], ['!', '.']],
	[['I plan for', 'I forget about', 'I lose'], ['the future', 'the past', 'the whatever'], ['which is coming soon', 'which is far off'], ['in a few minutes', 'in a few hours', 'in a few days'], ['or days', 'or months', 'or years'], ['!', '.']],
	[['I am inspired to', 'I don\'t want to', 'I am afraid to'], ['make', 'destroy', 'wreck'], ['and strengthen', 'and weaken', 'and slight'], ['friendships,', 'rivalries,', 'nemises,'], ['start', 'delay', 'stop'], ['and finish projects,', 'and leave things undone,', 'and lose track of projects,'], ['get outdoors,', 'hide in my cave,', 'waste away,'], ['clean up,', 'make a mess,', 'live in filth,'], ['dress well,', 'look like a slob,', 'look bad,'], ['and get in shape', 'and be lazy', 'and get fat'], ['!', '.']],
	[['I have', 'I miss', 'I\'ve lost'], ['the drive,', 'the doubt,', 'the apathy,'], ['energy,', 'sloth,', 'indolence,'], ['and determination', 'and indifference', 'and reluctance'], ['to be fit,', 'to be fat,', 'to be lazy,'], ['happy,', 'sad,', 'depressed,'], ['successful,', 'a failure,', 'a disappointment,'], ['respected,', 'pitied,', 'disdained,'], ['and loved', 'and hated', 'and lonely'], ['!', '.']],
	[['I picture myself', 'I force myself to be', 'I neglect myself as'], ['so happy that', 'so sad that', 'so despondent that'], ['every step\'s', 'no crawl\'s'], ['a dance', 'a slog', 'a stumble'], ['and every word\'s', 'and no grunt\'s'], ['a song', 'a burp', 'a weep'], ['!', '.']]
];
