happy.sentenceSpecs = [
	[['I sleep', 'I can\'t rest', 'I pace'], ['deeply', 'lightly', 'restlessly'], ['and rejuvenatingly', 'and fitfully', 'and irregularly'], ['when I want', 'at times I can\'t control'], ['!', '.']],
	[['I am safe,', 'I am in danger,', 'I am pursued,'], ['relaxed,', 'worried,', 'fearful,'], ['and in control', 'and overwhelmed', 'and helpless'], ['!', '.']],
	[['I rest', 'I work up', 'I tense'], ['and heal', 'and overwork', 'and strain'], ['myself', 'nothing'], ['when appropriate', 'when it\'s not needed', 'whenever'], ['!', '.']],
	[['Life has a rhythm;', 'Life is chaotic;', 'Life is patternless;'], ['there is a time to rejuvenate,', 'there is a time to collapse,', 'there is a time to giver up,'], ['a time to strive,', 'a time to yell,', 'a time to overexert,'], ['a time for confidence,', 'a time for hubris,', 'a time for ego,'], ['and a time for evaluation', 'and a time for doubt', 'and a time for paranoia'], ['!', '.']],
	[['I know,', 'I forget,', 'I am ignorant of,'], ['see,', 'am blind to,', 'miss,'], ['and feel', 'and ignore', 'brush aside'], ['all the benefits of', 'none of the shit for', 'no reason for'], ['a good night\'s sleep', 'of tossing and turning all night', 'of being on the internet all night'], ['!', '.']],
	[['I can', 'I can\'t', 'I won\'t'], ['relax', 'freak out', 'overreact'], ['when I want', 'never', 'at random times'], ['!', '.']],
	[['When well rested,', 'When running on empty,', 'With no sleep,'], ['I have so much energy', 'I am too tired', 'I am too worn out'], ['to be friendly,', 'to be shy,', 'to be cranky,'], ['productive,', 'lazy,', 'sloppy,'], ['active,', 'slothful,', 'fatigued,'], ['funny,', 'timid,', 'boring,'], ['patient,', 'grumpy,', 'crabby,'], ['kind,', 'mean,', 'detestable,'], ['and happy', 'and sad', 'and depressed'], ['!', '.']],
	[['I have', 'I lose', 'I avoid'], ['full days', 'empty days', 'meaningless days'], ['and restful nights', 'and fretful nights', 'and turbulent nights'], ['!', '.']],
	[['I am calm', 'I am nervous', 'I am worked up'], ['and relaxed', 'and hyper', 'and straining'], ['when sleeping', 'when pacing', 'when tossing and turning'], ['!', '.']],
	[['I picture', 'I can\'t imagine', 'I blank on'], ['soothing,', 'irritating,', 'riling'], ['tranquil,', 'busy,', 'choppy,'], ['serene,', 'chaotic,', 'confused,'], ['and placid things', 'and agitating things', 'and distress'], ['while falling asleep', 'while laying awake'], ['!', '.']]
];
