happy.sentenceSpecs = [
	/* Self-Esteem */ [['I have high', 'I have low', 'I don\'t have any'], ['self-esteem', 'self-doubt', 'self-loathing'], ['and my confidence', 'and my fear', 'and my insecurity'], ['can withstand', 'buckles to', 'whithers in front of'], ['anything', 'nothing'], ['!', '.']],
	/*relaxed around women*/  [['I am relaxed', 'I am nervous', 'I am agitated'], ['and confident', 'and self-conscious', 'and meek'], ['around people', 'when alone', 'around assholes'], ['including hot women', 'including ugly women', 'including plain women'], ['!', '.']],
	[['I have delightful,', 'I have awkward,', 'I avoid gawky'], ['entertaining,', 'boring,', 'repulsive,'], ['and interesting', 'and dull', 'and unstimulating'], ['conversations with', 'arguments with'], ['everyone', 'no one'], ['everywhere', 'nowhere'], ['!', '.']],
	[['I organize my thoughts', 'I jumble my thoughts', 'I scatter my thoughts'], ['and express them', 'and hide them', 'and muddle them'], ['clearly', 'hurriedly', 'murkily'], ['!','.']],
	/* get people to open up */ [['I get people to open up', 'I get people to close off', 'I force people to conceal'], ['by sharing with them', 'by bragging to them', 'by yelling at them'], ['appropriately and', 'inappropriately and', 'improperly and'], ['listening to them',  'ignoring them', 'rejecting them'], ['!', '.']],
	[['I intuit', 'I don\'t understand', 'I neglect'], ['kind,', 'hateful,', 'mean,'], ['helpful,', 'selfish,', 'hurting,'], ['uplifting,', 'depressing,', 'dismal,'], ['reactions to people', 'mutterings to myself'], ['!', '.']],
	[['I and', 'This weirdo and'], ['everyone', 'no one'], ['with me', 'against me'], ['has good', 'has bad', 'has no'], ['fun', 'sorrow', 'drudgery'], ['!', '.']],
	[['I sense', 'I miss', 'I overlook'], ['what others', 'what these jerks'], ['are really', 'are doubtfully', 'are disingenuously'],  ['feeling', 'insensitive to'], ['!', '.']],
	[['I perceive', 'I reject', 'I am deaf to'], ['the rhythm', 'the chaos', 'the cacophony'], ['of life', 'of death'], ['and conversation,', 'and rejection,'], ['I say', 'I withhold', 'I stammer'], ['the right things', 'the wrong things', 'careless things'], ['in the right', 'in the wrong', 'in the inappropriate'], ['time and place', 'drag and dump'], ['!', '.']],
	[['I am calm', 'I am frazzled', 'I am hyper'], ['and in control of', 'and overwhelmed with', 'and frightened by'], ['my level voice', 'my high pitch squeal', 'my garbled mutterings'], ['and confident body language', 'and nervous ticks', 'and constant fidgeting'], ['!', '.']],
];
